import AppKit
import SwiftUI
import Foundation

// This renders only the product's own test view. It neither observes the
// desktop nor accesses Keychain, actual profiles or system network settings.
@main struct SchedulerUIHarness {
    @MainActor static func main() throws {
        setenv("MPTCP_DESK_SMOKE_TEST", "1", 1)
        NSApplication.shared.setActivationPolicy(.prohibited)
        guard CommandLine.arguments.count == 3 else { throw ProfileError("usage: harness output-directory real-engine-telemetry-directory") }
        let output = URL(fileURLWithPath:CommandLine.arguments[1],isDirectory:true)
        let evidence = URL(fileURLWithPath:CommandLine.arguments[2],isDirectory:true)
        try FileManager.default.createDirectory(at:output,withIntermediateDirectories:true)
        let key = String(repeating:"a",count:64)
        let relays = [RelayRow(host:"192.0.2.10",port:24001),RelayRow(host:"198.51.100.20",port:24001)]
        let model = Model.shared
        var base = Profile(schema_version:3,mode:"userspace_multipath",listen_port:1081,relays:relays,udp_enabled:false,tcp_enabled:true,transport_key:key)
        try base.validate()
        let old = try JSONEncoder().encode(base)
        try model.loadProfileData(old)
        precondition(model.schedulerMode == "auto")
        let decodedOld=try JSONDecoder().decode(Profile.self,from:old)
        precondition(decodedOld.schedulerMode == "auto")
        let suite = "MPTCPDesk-Scheduler-Test-" + UUID().uuidString
        guard let defaults = UserDefaults(suiteName:suite) else {throw ProfileError("Test-only UserDefaults unavailable")}
        defer { defaults.removePersistentDomain(forName:suite) }
        var renders: [[String:Any]] = []
        func render(_ name:String) throws {
            let frame = NSRect(x:0,y:0,width:710,height:850)
            let host = NSHostingView(rootView:DesktopView().environment(\.colorScheme,.light))
            let window = NSWindow(contentRect:frame,styleMask:.borderless,backing:.buffered,defer:false)
            window.contentView=host;host.frame=frame
            host.layoutSubtreeIfNeeded()
            RunLoop.main.run(until:Date(timeIntervalSinceNow:0.25))
            host.layoutSubtreeIfNeeded();host.displayIfNeeded()
            precondition(host.bounds.width == 710 && host.bounds.height == 850)
            guard let bitmap = host.bitmapImageRepForCachingDisplay(in:host.bounds) else {throw ProfileError("No offscreen bitmap")}
            host.cacheDisplay(in:host.bounds,to:bitmap)
            guard let png = bitmap.representation(using:.png,properties:[:]) else {throw ProfileError("PNG failed")}
            try png.write(to:output.appendingPathComponent(name+".png"),options:.atomic)
            renders.append(["name":name,"width":bitmap.pixelsWide,"height":bitmap.pixelsHigh,"bytes":png.count,"configured":model.configuredSchedulerMode,"effective":model.effectiveSchedulerMode,"locked":model.configurationLocked])
            window.contentView=nil
        }
        for policy in SchedulerPolicy.allCases {
            var profile=base;profile.scheduler_mode=policy.rawValue
            if policy == .weighted {
                profile.relays = profile.relays.map { RelayRow(host:$0.host,port:$0.port,download_mbps:50,upload_mbps:nil) }
            }
            let raw=try JSONEncoder().encode(profile)
            try model.loadProfileData(raw)
            precondition(model.schedulerMode == policy.rawValue)
            let engineConfig=try model.profile()
            precondition(engineConfig.scheduler_mode == policy.rawValue)
            let ordinary=try profile.preferenceData()
            let object=try JSONSerialization.jsonObject(with:ordinary) as! [String:Any]
            precondition(object["transport_key"] == nil && object["scheduler_mode"] as? String == policy.rawValue)
            defaults.set(ordinary,forKey:"multipath-profile-v2")
            var restored=try JSONDecoder().decode(Profile.self,from:defaults.data(forKey:"multipath-profile-v2")!)
            restored.transport_key=key // synthetic only; never load the user's Keychain
            let fresh=Model();fresh.apply(restored)
            precondition(fresh.schedulerMode == policy.rawValue)
            // Evidence was generated by the production engine's main/run path,
            // with this policy received on stdin and acknowledged by Landing.
            let realData=try Data(contentsOf:evidence.appendingPathComponent("engine-"+policy.rawValue+".json"))
            let event=try JSONDecoder().decode(EngineEvent.self,from:realData)
            precondition(event.configured_scheduler_mode == policy.rawValue)
            precondition(event.sent! >= 1048576 && event.received! >= 1048576)
            model.receiveSchedulerEvent(event)
            model.tcpPaths=event.path_stats ?? []
            model.resources=event.resources;model.lifecycle=event.lifecycle
            precondition(model.configuredSchedulerMode == policy.rawValue)
            if policy != .auto { precondition(model.effectiveSchedulerMode == policy.rawValue) }
            precondition(!model.tcpPaths.isEmpty && model.tcpPaths.allSatisfy{$0.role != nil})
            model.tab=0;model.problem=nil;model.running=false;model.busy=false
            try render(policy.rawValue+"-configuration")
            model.tab=2
            try render(policy.rawValue+"-real-diagnostics")
            model.running=true
            precondition(model.configurationLocked && DesktopView().locked)
            do {try model.loadProfileData(old);fatalError("running import not locked")} catch is Model.Message {}
            precondition(model.schedulerMode == policy.rawValue)
            model.running=false;model.busy=true
            do {try model.loadProfileData(old);fatalError("busy import not locked")} catch is Model.Message {}
            model.tab=0
            try render(policy.rawValue+"-locked")
            model.busy=false
        }
        for invalid in ["", "AUTO", "other", "protect "] {
            base.scheduler_mode=invalid
            do {try base.validate();fatalError("invalid Userspace mode accepted")} catch is ProfileError {}
            do {try model.loadProfileData(JSONEncoder().encode(base));fatalError("invalid import accepted")} catch is ProfileError {}
        }
        base.mode="native_mptcp"
        try base.validate() // Native ignores the unused scheduler string.
        try model.loadProfileData(JSONEncoder().encode(base))
        precondition(!model.userspace && model.schedulerMode == "auto")
        let nativeProfile=try model.profile()
        precondition(nativeProfile.scheduler_mode == nil)
        model.tab=0
        try render("native-hides-userspace-policy")
        base.schema_version=2;base.mode="tcp_forward";base.transport_key=nil
        try model.loadProfileData(JSONEncoder().encode(base))
        precondition(!model.userspace && model.mode == "native_mptcp")
        let summary:[String:Any] = ["passed":true,"profile_schema":3,"default_scheduler":"auto","policies":SchedulerPolicy.allCases.map{$0.rawValue},"real_engine_telemetry_checked":true,"test_only_preferences_roundtrip":true,"keychain_accessed":false,"actual_desktop_observed":false,"renders":renders,"limits":"Offscreen own-view rendering and Model validation; not manual GUI clicks, system permissions or a production App/Surge run."]
        try JSONSerialization.data(withJSONObject:summary,options:[.prettyPrinted,.sortedKeys]).write(to:output.appendingPathComponent("SUMMARY.json"),options:.atomic)
        print("PASS: four policies including Weighted, real stdin-engine diagnostic decoding, absent/invalid/Native/legacy profiles, isolated preferences, running/busy guards and \(renders.count) offscreen views")
    }
}
