// Opt-in, temporary authenticated traffic fixture. It serves generated bytes
// only, never files or a general proxy. Not a third production deliverable.
package main

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"sync/atomic"
	"syscall"
	"time"
)

func main() {
	listen := flag.String("listen", "127.0.0.1:18081", "explicit test listener")
	tokenFile := flag.String("token-file", "", "private fixture token file")
	lifetime := flag.Int("lifetime", 2700, "automatic shutdown in seconds, maximum 3600")
	runID := flag.String("run-id", "mpx071-test", "public test run identifier")
	flag.Parse()
	token, e := os.ReadFile(*tokenFile)
	if e != nil {
		panic("private test token file unavailable")
	}
	token = []byte(strings.TrimSpace(string(token)))
	if len(token) < 32 || *lifetime < 60 || *lifetime > 3600 {
		panic("invalid fixture bounds")
	}
	started := time.Now()
	var active, requests, shorts, longs, bytesOut, writeErrors atomic.Int64
	slots := make(chan struct{}, 64)
	block := make([]byte, 32768)
	for i := range block {
		block[i] = byte((i*31 + (i >> 8) + 17) % 256)
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Connection", "close")
		w.Header().Set("Cache-Control", "no-store")
		if subtle.ConstantTimeCompare([]byte(r.Header.Get("X-MPX-Test-Token")), token) != 1 {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		select {
		case slots <- struct{}{}:
			defer func() { <-slots }()
		default:
			http.Error(w, "fixture concurrency limit", http.StatusServiceUnavailable)
			return
		}
		active.Add(1)
		defer active.Add(-1)
		requests.Add(1)
		w.Header().Set("X-MPX-Test-ID", *runID)
		if r.URL.Path == "/health" {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(map[string]any{"run_id": *runID, "uptime_seconds": time.Since(started).Seconds(), "active": active.Load(), "requests": requests.Load(), "shorts": shorts.Load(), "longs": longs.Load(), "bytes": bytesOut.Load(), "write_errors": writeErrors.Load()})
			return
		}
		n := int64(1537)
		duration := time.Duration(0)
		switch r.URL.Path {
		case "/short":
			shorts.Add(1)
		case "/stream":
			seconds, err := strconv.Atoi(r.URL.Query().Get("seconds"))
			if err != nil || seconds < 1 || seconds > 1860 {
				http.Error(w, "seconds must be 1..1860", 400)
				return
			}
			duration = time.Duration(seconds) * time.Second
			longs.Add(1)
		case "/bytes":
			count, err := strconv.ParseInt(r.URL.Query().Get("n"), 10, 64)
			if err != nil || count < 0 || count > 8<<30 {
				http.Error(w, "n outside fixture limit", 400)
				return
			}
			n = count
			longs.Add(1)
		default:
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", "application/octet-stream")
		if duration == 0 {
			w.Header().Set("Content-Length", strconv.FormatInt(n, 10))
		}
		if r.Method == "HEAD" {
			return
		}
		if r.Method != "GET" {
			http.Error(w, "GET only", 405)
			return
		}
		begin := time.Now()
		sent := int64(0)
		for (duration > 0 && time.Since(begin) < duration) || (duration == 0 && sent < n) {
			select {
			case <-r.Context().Done():
				return
			default:
			}
			size := len(block)
			if duration == 0 {
				size = int(min(int64(size), n-sent))
			}
			http.NewResponseController(w).SetWriteDeadline(time.Now().Add(15 * time.Second))
			count, err := w.Write(block[:size])
			sent += int64(count)
			bytesOut.Add(int64(count))
			if err != nil {
				writeErrors.Add(1)
				return
			}
		}
	})
	server := &http.Server{Addr: *listen, Handler: mux, ReadHeaderTimeout: 5 * time.Second, ReadTimeout: 10 * time.Second, IdleTimeout: 5 * time.Second, MaxHeaderBytes: 8192}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	timeout, cancel := context.WithTimeout(ctx, time.Duration(*lifetime)*time.Second)
	defer cancel()
	go func() {
		<-timeout.Done()
		c, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		server.Shutdown(c)
	}()
	fmt.Printf("temporary fixture run=%s lifetime=%ds\n", *runID, *lifetime)
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	json.NewEncoder(os.Stdout).Encode(map[string]any{"run_id": *runID, "bytes": bytesOut.Load(), "requests": requests.Load(), "shorts": shorts.Load(), "longs": longs.Load(), "write_errors": writeErrors.Load()})
}
